-- GENERATED FILE -- edit shared/seed-data.js and run `npm run build:seed`.
--
-- Loaded once when the site is first set up. Safe to re-run: every statement
-- is INSERT OR IGNORE, so it will not duplicate or overwrite real club data.

-- Badges
INSERT OR IGNORE INTO badges (name, emoji, description, color) VALUES ('Hackathon Winner', '🏆', 'Placed at a hackathon', 'amber');
INSERT OR IGNORE INTO badges (name, emoji, description, color) VALUES ('CTF Champ', '🛡️', 'Top finish in a capture-the-flag event', 'emerald');
INSERT OR IGNORE INTO badges (name, emoji, description, color) VALUES ('Open Sourcerer', '🧙', 'Merged a pull request into a real open-source project', 'violet');
INSERT OR IGNORE INTO badges (name, emoji, description, color) VALUES ('Mentor', '🤝', 'Taught or tutored other club members', 'sky');
INSERT OR IGNORE INTO badges (name, emoji, description, color) VALUES ('Competitive Programmer', '⚡', 'Competed in USACO, ACSL, or Codeforces', 'rose');
INSERT OR IGNORE INTO badges (name, emoji, description, color) VALUES ('Shipped It', '🚀', 'Launched a project other people actually use', 'orange');
INSERT OR IGNORE INTO badges (name, emoji, description, color) VALUES ('Perfect Attendance', '📅', 'Attended every meeting this semester', 'teal');
INSERT OR IGNORE INTO badges (name, emoji, description, color) VALUES ('Founder', '🌱', 'Founding member of the club', 'lime');

-- Demo members. Delete these from the admin panel once real members are added.
INSERT OR IGNORE INTO students (id, name, grade, avatar_seed) VALUES (1, 'Ava Chen', 12, 'avachen');
INSERT INTO point_events (student_id, delta, reason) SELECT 1, 60, 'Won district hackathon' WHERE NOT EXISTS (SELECT 1 FROM point_events WHERE student_id = 1 AND reason = 'Won district hackathon');
INSERT INTO point_events (student_id, delta, reason) SELECT 1, 25, 'Led intro-to-Python workshop' WHERE NOT EXISTS (SELECT 1 FROM point_events WHERE student_id = 1 AND reason = 'Led intro-to-Python workshop');
INSERT INTO point_events (student_id, delta, reason) SELECT 1, 20, 'USACO Silver promotion' WHERE NOT EXISTS (SELECT 1 FROM point_events WHERE student_id = 1 AND reason = 'USACO Silver promotion');
INSERT INTO point_events (student_id, delta, reason) SELECT 1, 15, 'Meeting attendance' WHERE NOT EXISTS (SELECT 1 FROM point_events WHERE student_id = 1 AND reason = 'Meeting attendance');
INSERT OR IGNORE INTO student_badges (student_id, badge_id) SELECT 1, id FROM badges WHERE name = 'Hackathon Winner';
INSERT OR IGNORE INTO student_badges (student_id, badge_id) SELECT 1, id FROM badges WHERE name = 'Mentor';
INSERT OR IGNORE INTO student_badges (student_id, badge_id) SELECT 1, id FROM badges WHERE name = 'Competitive Programmer';
INSERT OR IGNORE INTO students (id, name, grade, avatar_seed) VALUES (2, 'Marcus Webb', 11, 'marcuswebb');
INSERT INTO point_events (student_id, delta, reason) SELECT 2, 50, 'picoCTF top 5% finish' WHERE NOT EXISTS (SELECT 1 FROM point_events WHERE student_id = 2 AND reason = 'picoCTF top 5% finish');
INSERT INTO point_events (student_id, delta, reason) SELECT 2, 30, 'Built club website' WHERE NOT EXISTS (SELECT 1 FROM point_events WHERE student_id = 2 AND reason = 'Built club website');
INSERT INTO point_events (student_id, delta, reason) SELECT 2, 15, 'Meeting attendance' WHERE NOT EXISTS (SELECT 1 FROM point_events WHERE student_id = 2 AND reason = 'Meeting attendance');
INSERT INTO point_events (student_id, delta, reason) SELECT 2, 10, 'Brought a guest speaker' WHERE NOT EXISTS (SELECT 1 FROM point_events WHERE student_id = 2 AND reason = 'Brought a guest speaker');
INSERT OR IGNORE INTO student_badges (student_id, badge_id) SELECT 2, id FROM badges WHERE name = 'CTF Champ';
INSERT OR IGNORE INTO student_badges (student_id, badge_id) SELECT 2, id FROM badges WHERE name = 'Shipped It';
INSERT OR IGNORE INTO students (id, name, grade, avatar_seed) VALUES (3, 'Priya Raman', 12, 'priyaraman');
INSERT INTO point_events (student_id, delta, reason) SELECT 3, 40, 'Congressional App Challenge submission' WHERE NOT EXISTS (SELECT 1 FROM point_events WHERE student_id = 3 AND reason = 'Congressional App Challenge submission');
INSERT INTO point_events (student_id, delta, reason) SELECT 3, 25, 'Merged PR into open source' WHERE NOT EXISTS (SELECT 1 FROM point_events WHERE student_id = 3 AND reason = 'Merged PR into open source');
INSERT INTO point_events (student_id, delta, reason) SELECT 3, 20, 'Mentored two freshmen' WHERE NOT EXISTS (SELECT 1 FROM point_events WHERE student_id = 3 AND reason = 'Mentored two freshmen');
INSERT INTO point_events (student_id, delta, reason) SELECT 3, 10, 'Meeting attendance' WHERE NOT EXISTS (SELECT 1 FROM point_events WHERE student_id = 3 AND reason = 'Meeting attendance');
INSERT OR IGNORE INTO student_badges (student_id, badge_id) SELECT 3, id FROM badges WHERE name = 'Open Sourcerer';
INSERT OR IGNORE INTO student_badges (student_id, badge_id) SELECT 3, id FROM badges WHERE name = 'Mentor';
INSERT OR IGNORE INTO students (id, name, grade, avatar_seed) VALUES (4, 'Diego Alvarez', 10, 'diegoalvarez');
INSERT INTO point_events (student_id, delta, reason) SELECT 4, 35, 'Second place, Collin College coding contest' WHERE NOT EXISTS (SELECT 1 FROM point_events WHERE student_id = 4 AND reason = 'Second place, Collin College coding contest');
INSERT INTO point_events (student_id, delta, reason) SELECT 4, 20, 'Robotics build team' WHERE NOT EXISTS (SELECT 1 FROM point_events WHERE student_id = 4 AND reason = 'Robotics build team');
INSERT INTO point_events (student_id, delta, reason) SELECT 4, 15, 'Meeting attendance' WHERE NOT EXISTS (SELECT 1 FROM point_events WHERE student_id = 4 AND reason = 'Meeting attendance');
INSERT OR IGNORE INTO student_badges (student_id, badge_id) SELECT 4, id FROM badges WHERE name = 'Competitive Programmer';
INSERT OR IGNORE INTO students (id, name, grade, avatar_seed) VALUES (5, 'Sofia Nguyen', 11, 'sofianguyen');
INSERT INTO point_events (student_id, delta, reason) SELECT 5, 30, 'Ran the club Discord bot project' WHERE NOT EXISTS (SELECT 1 FROM point_events WHERE student_id = 5 AND reason = 'Ran the club Discord bot project');
INSERT INTO point_events (student_id, delta, reason) SELECT 5, 20, 'Science fair qualifier' WHERE NOT EXISTS (SELECT 1 FROM point_events WHERE student_id = 5 AND reason = 'Science fair qualifier');
INSERT INTO point_events (student_id, delta, reason) SELECT 5, 12, 'Meeting attendance' WHERE NOT EXISTS (SELECT 1 FROM point_events WHERE student_id = 5 AND reason = 'Meeting attendance');
INSERT OR IGNORE INTO student_badges (student_id, badge_id) SELECT 5, id FROM badges WHERE name = 'Shipped It';
INSERT OR IGNORE INTO students (id, name, grade, avatar_seed) VALUES (6, 'Jalen Brooks', 9, 'jalenbrooks');
INSERT INTO point_events (student_id, delta, reason) SELECT 6, 25, 'Completed CS50x problem set 5' WHERE NOT EXISTS (SELECT 1 FROM point_events WHERE student_id = 6 AND reason = 'Completed CS50x problem set 5');
INSERT INTO point_events (student_id, delta, reason) SELECT 6, 15, 'Meeting attendance' WHERE NOT EXISTS (SELECT 1 FROM point_events WHERE student_id = 6 AND reason = 'Meeting attendance');
INSERT INTO point_events (student_id, delta, reason) SELECT 6, 10, 'Helped set up club fair booth' WHERE NOT EXISTS (SELECT 1 FROM point_events WHERE student_id = 6 AND reason = 'Helped set up club fair booth');
INSERT OR IGNORE INTO student_badges (student_id, badge_id) SELECT 6, id FROM badges WHERE name = 'Perfect Attendance';
INSERT OR IGNORE INTO students (id, name, grade, avatar_seed) VALUES (7, 'Hana Kim', 10, 'hanakim');
INSERT INTO point_events (student_id, delta, reason) SELECT 7, 22, 'Technovation team submission' WHERE NOT EXISTS (SELECT 1 FROM point_events WHERE student_id = 7 AND reason = 'Technovation team submission');
INSERT INTO point_events (student_id, delta, reason) SELECT 7, 18, 'Meeting attendance' WHERE NOT EXISTS (SELECT 1 FROM point_events WHERE student_id = 7 AND reason = 'Meeting attendance');
INSERT OR IGNORE INTO students (id, name, grade, avatar_seed) VALUES (8, 'Omar Haddad', 12, 'omarhaddad');
INSERT INTO point_events (student_id, delta, reason) SELECT 8, 20, 'Taught Git workshop' WHERE NOT EXISTS (SELECT 1 FROM point_events WHERE student_id = 8 AND reason = 'Taught Git workshop');
INSERT INTO point_events (student_id, delta, reason) SELECT 8, 15, 'Meeting attendance' WHERE NOT EXISTS (SELECT 1 FROM point_events WHERE student_id = 8 AND reason = 'Meeting attendance');
INSERT OR IGNORE INTO student_badges (student_id, badge_id) SELECT 8, id FROM badges WHERE name = 'Mentor';
INSERT OR IGNORE INTO student_badges (student_id, badge_id) SELECT 8, id FROM badges WHERE name = 'Founder';
INSERT OR IGNORE INTO students (id, name, grade, avatar_seed) VALUES (9, 'Grace Miller', 9, 'gracemiller');
INSERT INTO point_events (student_id, delta, reason) SELECT 9, 18, 'First project demo' WHERE NOT EXISTS (SELECT 1 FROM point_events WHERE student_id = 9 AND reason = 'First project demo');
INSERT INTO point_events (student_id, delta, reason) SELECT 9, 10, 'Meeting attendance' WHERE NOT EXISTS (SELECT 1 FROM point_events WHERE student_id = 9 AND reason = 'Meeting attendance');
INSERT OR IGNORE INTO students (id, name, grade, avatar_seed) VALUES (10, 'Ethan Park', 11, 'ethanpark');
INSERT INTO point_events (student_id, delta, reason) SELECT 10, 12, 'Meeting attendance' WHERE NOT EXISTS (SELECT 1 FROM point_events WHERE student_id = 10 AND reason = 'Meeting attendance');
INSERT INTO point_events (student_id, delta, reason) SELECT 10, 8, 'Club t-shirt design' WHERE NOT EXISTS (SELECT 1 FROM point_events WHERE student_id = 10 AND reason = 'Club t-shirt design');

-- Verified opportunity catalogue
INSERT OR IGNORE INTO opportunities (title, org, description, url, type, cost, format, location, lat, lng, distance_mi, age_min, age_max, source, status, fingerprint) VALUES ('UT Dallas Summer Programs for High School Students', 'The University of Texas at Dallas', 'Week-long summer camps in computer science, cybersecurity, engineering, and game design on the UTD campus in Richardson. The closest major research university to Plano East.', 'https://www.utdallas.edu/k12/', 'program', 'paid', 'local', 'UT Dallas, 800 W Campbell Rd, Richardson, TX 75080', 32.9857, -96.7501, 5.8, 14, 18, 'seed', 'live', 'utdallas.edu|ut dallas summer programs for high school students');
INSERT OR IGNORE INTO opportunities (title, org, description, url, type, cost, format, location, lat, lng, distance_mi, age_min, age_max, source, status, fingerprint) VALUES ('Clark Summer Research Program', 'UT Dallas / Eugene McDermott Foundation', 'Paid summer research placement for rising high school seniors, working alongside UT Dallas faculty in science and engineering labs. Highly competitive and fully funded.', 'https://www.utdallas.edu/clark/', 'internship', 'stipend', 'local', 'UT Dallas, 800 W Campbell Rd, Richardson, TX 75080', 32.9857, -96.7501, 5.8, 16, 18, 'seed', 'live', 'utdallas.edu|clark summer research program');
INSERT OR IGNORE INTO opportunities (title, org, description, url, type, cost, format, location, lat, lng, distance_mi, age_min, age_max, source, status, fingerprint) VALUES ('Collin College Dual Credit — Computer Science', 'Collin College', 'Take real college CS courses while still in high school and earn credit for both. The Plano campus is about two miles from Plano East. Tuition is often covered through Plano ISD.', 'https://www.collin.edu/gettingstarted/dualcredit/', 'program', 'free', 'local', 'Collin College Plano Campus, 2800 E Spring Creek Pkwy, Plano, TX 75074', 33.057, -96.687, 1.8, 14, 18, 'seed', 'live', 'collin.edu|collin college dual credit — computer science');
INSERT OR IGNORE INTO opportunities (title, org, description, url, type, cost, format, location, lat, lng, distance_mi, age_min, age_max, source, status, fingerprint) VALUES ('Collin College Youth & Summer Enrichment Camps', 'Collin College Continuing Education', 'Short, affordable summer camps in coding, robotics, and 3D design across the Plano, Frisco, and McKinney campuses.', 'https://www.collin.edu/ce/', 'program', 'paid', 'local', 'Collin College Frisco Campus, 9700 Wade Blvd, Frisco, TX 75035', 33.117, -96.81, 9.9, 14, 17, 'seed', 'live', 'collin.edu|collin college youth & summer enrichment camps');
INSERT OR IGNORE INTO opportunities (title, org, description, url, type, cost, format, location, lat, lng, distance_mi, age_min, age_max, source, status, fingerprint) VALUES ('Plano Public Library Makerspace & Tech Programs', 'City of Plano', 'Free access to 3D printers, laser cutters, and electronics kits, plus free teen tech workshops. A Plano library card is all you need.', 'https://library.plano.gov/', 'resource', 'free', 'local', 'Davis Library, 7501 Independence Pkwy, Plano, TX 75025', 33.057, -96.75, 4.9, 14, 17, 'seed', 'live', 'library.plano.gov|plano public library makerspace & tech programs');
INSERT OR IGNORE INTO opportunities (title, org, description, url, type, cost, format, location, lat, lng, distance_mi, age_min, age_max, source, status, fingerprint) VALUES ('Dallas College Richland — Tech Dual Credit & Camps', 'Dallas College', 'Dual credit pathways and short technology courses in networking, programming, and IT support at the Richland campus in north Dallas.', 'https://www.dallascollege.edu/', 'program', 'free', 'local', 'Dallas College Richland Campus, 12800 Abrams Rd, Dallas, TX 75243', 32.927, -96.72, 8.1, 14, 18, 'seed', 'live', 'dallascollege.edu|dallas college richland — tech dual credit & camps');
INSERT OR IGNORE INTO opportunities (title, org, description, url, type, cost, format, location, lat, lng, distance_mi, age_min, age_max, source, status, fingerprint) VALUES ('Allen Public Library Teen Tech Programs', 'City of Allen', 'Free teen coding clubs, robotics nights, and maker sessions a short drive north of Plano.', 'https://www.allentx.gov/234/Library', 'resource', 'free', 'local', 'Allen Public Library, 300 N Allen Dr, Allen, TX 75013', 33.103, -96.67, 4.7, 14, 17, 'seed', 'live', 'allentx.gov|allen public library teen tech programs');
INSERT OR IGNORE INTO opportunities (title, org, description, url, type, cost, format, location, lat, lng, distance_mi, age_min, age_max, source, status, fingerprint) VALUES ('USA Computing Olympiad (USACO)', 'USACO', 'Free online competitive programming contests four times a year. Start at Bronze and promote through Silver, Gold, and Platinum. The single best resume line in high school CS.', 'https://usaco.org/', 'competition', 'free', 'online', '', NULL, NULL, NULL, 14, 18, 'seed', 'live', 'usaco.org|usa computing olympiad (usaco)');
INSERT OR IGNORE INTO opportunities (title, org, description, url, type, cost, format, location, lat, lng, distance_mi, age_min, age_max, source, status, fingerprint) VALUES ('picoCTF', 'Carnegie Mellon University', 'Free beginner-friendly cybersecurity capture-the-flag competition, with a year-round practice gym of hundreds of challenges. No experience required.', 'https://picoctf.org/', 'competition', 'free', 'online', '', NULL, NULL, NULL, 14, 18, 'seed', 'live', 'picoctf.org|picoctf');
INSERT OR IGNORE INTO opportunities (title, org, description, url, type, cost, format, location, lat, lng, distance_mi, age_min, age_max, source, status, fingerprint) VALUES ('Congressional App Challenge', 'U.S. House of Representatives', 'Build an app and submit it in your congressional district. Plano is split across TX-03 and TX-32, and district-level fields are small, so the odds are genuinely good. Winners are recognized in Washington.', 'https://www.congressionalappchallenge.us/', 'competition', 'free', 'online', '', NULL, NULL, NULL, 14, 18, 'seed', 'live', 'congressionalappchallenge.us|congressional app challenge');
INSERT OR IGNORE INTO opportunities (title, org, description, url, type, cost, format, location, lat, lng, distance_mi, age_min, age_max, source, status, fingerprint) VALUES ('MIT THINK Scholars Program', 'MIT', 'Submit a proposal for a science or engineering project you have not built yet. Finalists get funding, mentorship from MIT students, and a trip to campus.', 'https://think.mit.edu/', 'competition', 'free', 'online', '', NULL, NULL, NULL, 14, 18, 'seed', 'live', 'think.mit.edu|mit think scholars program');
INSERT OR IGNORE INTO opportunities (title, org, description, url, type, cost, format, location, lat, lng, distance_mi, age_min, age_max, source, status, fingerprint) VALUES ('CyberPatriot National Youth Cyber Defense Competition', 'Air & Space Forces Association', 'Team-based cyber defense competition where you harden vulnerable virtual machines against attack. Great fit for a club to enter together.', 'https://www.uscyberpatriot.org/', 'competition', 'free', 'online', '', NULL, NULL, NULL, 14, 18, 'seed', 'live', 'uscyberpatriot.org|cyberpatriot national youth cyber defense competition');
INSERT OR IGNORE INTO opportunities (title, org, description, url, type, cost, format, location, lat, lng, distance_mi, age_min, age_max, source, status, fingerprint) VALUES ('Technovation Girls', 'Technovation', 'Free global program where teams of girls build a mobile app or AI project addressing a community problem, supported by industry mentors.', 'https://www.technovation.org/', 'competition', 'free', 'online', '', NULL, NULL, NULL, 14, 18, 'seed', 'live', 'technovation.org|technovation girls');
INSERT OR IGNORE INTO opportunities (title, org, description, url, type, cost, format, location, lat, lng, distance_mi, age_min, age_max, source, status, fingerprint) VALUES ('American Computer Science League (ACSL)', 'ACSL', 'Short written and programming contests run in rounds throughout the school year. A low-pressure way for a club to start competing together.', 'https://www.acsl.org/', 'competition', 'paid', 'online', '', NULL, NULL, NULL, 14, 18, 'seed', 'live', 'acsl.org|american computer science league (acsl)');
INSERT OR IGNORE INTO opportunities (title, org, description, url, type, cost, format, location, lat, lng, distance_mi, age_min, age_max, source, status, fingerprint) VALUES ('Conrad Challenge', 'Conrad Foundation', 'Team innovation competition where you design a product or venture around a real-world problem in areas like cyber-technology, health, and energy.', 'https://www.conradchallenge.org/', 'competition', 'free', 'online', '', NULL, NULL, NULL, 13, 18, 'seed', 'live', 'conradchallenge.org|conrad challenge');
INSERT OR IGNORE INTO opportunities (title, org, description, url, type, cost, format, location, lat, lng, distance_mi, age_min, age_max, source, status, fingerprint) VALUES ('Regeneron International Science and Engineering Fair (ISEF)', 'Society for Science', 'The largest pre-college science competition in the world. Qualify through a regional fair first — the Dallas regional fair is the local entry point.', 'https://www.societyforscience.org/isef/', 'competition', 'free', 'online', '', NULL, NULL, NULL, 14, 18, 'seed', 'live', 'societyforscience.org|regeneron international science and engineering fair (isef)');
INSERT OR IGNORE INTO opportunities (title, org, description, url, type, cost, format, location, lat, lng, distance_mi, age_min, age_max, source, status, fingerprint) VALUES ('NASA High School Internships (OSTEM)', 'NASA', 'Paid NASA internships open to high school students aged 16 and up, including remote placements. Johnson Space Center in Houston also hosts Texas students.', 'https://www.nasa.gov/learning-resources/internship-programs/', 'internship', 'stipend', 'online', '', NULL, NULL, NULL, 16, 18, 'seed', 'live', 'nasa.gov|nasa high school internships (ostem)');
INSERT OR IGNORE INTO opportunities (title, org, description, url, type, cost, format, location, lat, lng, distance_mi, age_min, age_max, source, status, fingerprint) VALUES ('Girls Who Code Summer Programs', 'Girls Who Code', 'Free virtual summer programs teaching CS fundamentals, web development, and data science, with no prior experience required.', 'https://girlswhocode.com/programs', 'program', 'free', 'online', '', NULL, NULL, NULL, 14, 18, 'seed', 'live', 'girlswhocode.com|girls who code summer programs');
INSERT OR IGNORE INTO opportunities (title, org, description, url, type, cost, format, location, lat, lng, distance_mi, age_min, age_max, source, status, fingerprint) VALUES ('Kode With Klossy', 'Kode With Klossy', 'Free two-week coding camps for girls and gender-expansive teens, covering web development, mobile apps, and machine learning.', 'https://www.kodewithklossy.com/', 'program', 'free', 'online', '', NULL, NULL, NULL, 13, 18, 'seed', 'live', 'kodewithklossy.com|kode with klossy');
INSERT OR IGNORE INTO opportunities (title, org, description, url, type, cost, format, location, lat, lng, distance_mi, age_min, age_max, source, status, fingerprint) VALUES ('Hack Club', 'Hack Club', 'A worldwide network of high school hackers. Free hardware grants, hackathons, and an extremely active Slack. Useful for running our own club better, too.', 'https://hackclub.com/', 'resource', 'free', 'online', '', NULL, NULL, NULL, 14, 18, 'seed', 'live', 'hackclub.com|hack club');
INSERT OR IGNORE INTO opportunities (title, org, description, url, type, cost, format, location, lat, lng, distance_mi, age_min, age_max, source, status, fingerprint) VALUES ('CS50x — Introduction to Computer Science', 'Harvard University (edX)', 'Harvard''s flagship CS course, free and self-paced. C, Python, SQL, and web development. The best free foundation you can get before college.', 'https://cs50.harvard.edu/x/', 'resource', 'free', 'online', '', NULL, NULL, NULL, 14, 18, 'seed', 'live', 'cs50.harvard.edu|cs50x — introduction to computer science');
INSERT OR IGNORE INTO opportunities (title, org, description, url, type, cost, format, location, lat, lng, distance_mi, age_min, age_max, source, status, fingerprint) VALUES ('freeCodeCamp', 'freeCodeCamp', 'Thousands of hours of free, project-based curriculum in web development, data analysis, and machine learning, with free certifications.', 'https://www.freecodecamp.org/', 'resource', 'free', 'online', '', NULL, NULL, NULL, 14, 18, 'seed', 'live', 'freecodecamp.org|freecodecamp');
INSERT OR IGNORE INTO opportunities (title, org, description, url, type, cost, format, location, lat, lng, distance_mi, age_min, age_max, source, status, fingerprint) VALUES ('Codeforces', 'Codeforces', 'Free competitive programming contests roughly twice a week, with an enormous problem archive. The best place to practice between USACO rounds.', 'https://codeforces.com/', 'resource', 'free', 'online', '', NULL, NULL, NULL, 14, 18, 'seed', 'live', 'codeforces.com|codeforces');
INSERT OR IGNORE INTO opportunities (title, org, description, url, type, cost, format, location, lat, lng, distance_mi, age_min, age_max, source, status, fingerprint) VALUES ('GenCyber Summer Camps', 'NSA & National Science Foundation', 'Free cybersecurity camps funded by the NSA and NSF, hosted at universities nationwide including several in Texas. Free to attend, no cost to students.', 'https://www.gen-cyber.com/', 'program', 'free', 'online', '', NULL, NULL, NULL, 14, 18, 'seed', 'live', 'gen-cyber.com|gencyber summer camps');
INSERT OR IGNORE INTO opportunities (title, org, description, url, type, cost, format, location, lat, lng, distance_mi, age_min, age_max, source, status, fingerprint) VALUES ('Science Olympiad', 'Science Olympiad', 'Team STEM competition spanning 23 events, including several computing and engineering builds. Texas has a strong regional and state circuit.', 'https://www.soinc.org/', 'competition', 'paid', 'online', '', NULL, NULL, NULL, 14, 18, 'seed', 'live', 'soinc.org|science olympiad');
INSERT OR IGNORE INTO opportunities (title, org, description, url, type, cost, format, location, lat, lng, distance_mi, age_min, age_max, source, status, fingerprint) VALUES ('FIRST Robotics Competition', 'FIRST', 'Build a competition robot in six weeks with a team. North Texas hosts one of the largest FIRST districts in the country, with events across DFW.', 'https://www.firstinspires.org/robotics/frc', 'competition', 'paid', 'online', '', NULL, NULL, NULL, 14, 18, 'seed', 'live', 'firstinspires.org|first robotics competition');
INSERT OR IGNORE INTO opportunities (title, org, description, url, type, cost, format, location, lat, lng, distance_mi, age_min, age_max, source, status, fingerprint) VALUES ('MIT Beaver Works Summer Institute', 'MIT Lincoln Laboratory', 'Free four-week summer program in autonomous racing, machine learning, cybersecurity, and more. Fully funded — MIT covers tuition and housing for accepted students.', 'https://beaverworks.ll.mit.edu/CMS/bw/bwsi', 'program', 'free', 'residential', 'MIT, Cambridge, MA', NULL, NULL, NULL, 16, 18, 'seed', 'live', 'beaverworks.ll.mit.edu|mit beaver works summer institute');
INSERT OR IGNORE INTO opportunities (title, org, description, url, type, cost, format, location, lat, lng, distance_mi, age_min, age_max, source, status, fingerprint) VALUES ('MITES Summer', 'MIT', 'Free, rigorous six-week residential STEM program for rising seniors from underrepresented or underserved backgrounds. MIT covers essentially all costs.', 'https://mites.mit.edu/', 'program', 'free', 'residential', 'MIT, Cambridge, MA', NULL, NULL, NULL, 16, 18, 'seed', 'live', 'mites.mit.edu|mites summer');
INSERT OR IGNORE INTO opportunities (title, org, description, url, type, cost, format, location, lat, lng, distance_mi, age_min, age_max, source, status, fingerprint) VALUES ('Research Science Institute (RSI)', 'Center for Excellence in Education & MIT', 'Free six-week summer research program for rising seniors, widely regarded as the most selective STEM summer program in the United States. Fully funded.', 'https://www.cee.org/programs/research-science-institute', 'internship', 'free', 'residential', 'MIT, Cambridge, MA', NULL, NULL, NULL, 16, 18, 'seed', 'live', 'cee.org|research science institute (rsi)');
INSERT OR IGNORE INTO opportunities (title, org, description, url, type, cost, format, location, lat, lng, distance_mi, age_min, age_max, source, status, fingerprint) VALUES ('Summer Science Program (SSP)', 'Summer Science Program', 'Residential research program in astrophysics, biochemistry, or genomics where teams complete an original research project. Need-blind admission with generous financial aid.', 'https://summerscience.org/', 'program', 'paid', 'residential', 'Various university campuses, USA', NULL, NULL, NULL, 15, 18, 'seed', 'live', 'summerscience.org|summer science program (ssp)');

-- Officers
INSERT INTO officers (name, role, note, committee, sort_order) SELECT 'Elliott Harper', 'President', 'Also an officer on the Cybersecurity Committee', 'main', 0 WHERE NOT EXISTS (SELECT 1 FROM officers WHERE name = 'Elliott Harper');
INSERT INTO officers (name, role, note, committee, sort_order) SELECT 'Sujay Gonchigar', 'Vice President', 'Main CS Club', 'main', 1 WHERE NOT EXISTS (SELECT 1 FROM officers WHERE name = 'Sujay Gonchigar');
INSERT INTO officers (name, role, note, committee, sort_order) SELECT 'Keshav Anand', 'Lead Officer, Cybersecurity', 'Runs the Cyber Committee', 'cyber', 2 WHERE NOT EXISTS (SELECT 1 FROM officers WHERE name = 'Keshav Anand');
INSERT INTO officers (name, role, note, committee, sort_order) SELECT 'Cody Trainer', 'Officer', 'Main CS Club', 'main', 3 WHERE NOT EXISTS (SELECT 1 FROM officers WHERE name = 'Cody Trainer');
INSERT INTO officers (name, role, note, committee, sort_order) SELECT 'Marcus Benett Zaens', 'Officer', 'Main CS Club', 'main', 4 WHERE NOT EXISTS (SELECT 1 FROM officers WHERE name = 'Marcus Benett Zaens');
INSERT INTO officers (name, role, note, committee, sort_order) SELECT 'Zubair Ahmed', 'Officer', 'Main CS Club', 'main', 5 WHERE NOT EXISTS (SELECT 1 FROM officers WHERE name = 'Zubair Ahmed');

-- Curriculum roadmap
INSERT INTO curriculum_topics (track, title, sort_order) SELECT 'fall', 'Print statements and data types', 0 WHERE NOT EXISTS (SELECT 1 FROM curriculum_topics WHERE track = 'fall' AND title = 'Print statements and data types');
INSERT INTO curriculum_topics (track, title, sort_order) SELECT 'fall', 'Conditionals and loops', 1 WHERE NOT EXISTS (SELECT 1 FROM curriculum_topics WHERE track = 'fall' AND title = 'Conditionals and loops');
INSERT INTO curriculum_topics (track, title, sort_order) SELECT 'fall', 'Arrays and strings', 2 WHERE NOT EXISTS (SELECT 1 FROM curriculum_topics WHERE track = 'fall' AND title = 'Arrays and strings');
INSERT INTO curriculum_topics (track, title, sort_order) SELECT 'fall', 'Object-oriented programming', 3 WHERE NOT EXISTS (SELECT 1 FROM curriculum_topics WHERE track = 'fall' AND title = 'Object-oriented programming');
INSERT INTO curriculum_topics (track, title, sort_order) SELECT 'fall', 'Recursion', 4 WHERE NOT EXISTS (SELECT 1 FROM curriculum_topics WHERE track = 'fall' AND title = 'Recursion');
INSERT INTO curriculum_topics (track, title, sort_order) SELECT 'spring', 'Searching and sorting', 0 WHERE NOT EXISTS (SELECT 1 FROM curriculum_topics WHERE track = 'spring' AND title = 'Searching and sorting');
INSERT INTO curriculum_topics (track, title, sort_order) SELECT 'spring', 'Time complexity analysis', 1 WHERE NOT EXISTS (SELECT 1 FROM curriculum_topics WHERE track = 'spring' AND title = 'Time complexity analysis');
INSERT INTO curriculum_topics (track, title, sort_order) SELECT 'spring', 'Data structures', 2 WHERE NOT EXISTS (SELECT 1 FROM curriculum_topics WHERE track = 'spring' AND title = 'Data structures');
INSERT INTO curriculum_topics (track, title, sort_order) SELECT 'spring', 'Graphs and BFS', 3 WHERE NOT EXISTS (SELECT 1 FROM curriculum_topics WHERE track = 'spring' AND title = 'Graphs and BFS');
INSERT INTO curriculum_topics (track, title, sort_order) SELECT 'spring', 'Dynamic programming', 4 WHERE NOT EXISTS (SELECT 1 FROM curriculum_topics WHERE track = 'spring' AND title = 'Dynamic programming');

-- Competitions
INSERT INTO competitions (name, description, result, event_date, url, status, sort_order) SELECT 'UIL Computer Science', 'District, region, state. A written test plus a team programming round.', '', NULL, '', 'upcoming', 0 WHERE NOT EXISTS (SELECT 1 FROM competitions WHERE name = 'UIL Computer Science');
INSERT INTO competitions (name, description, result, event_date, url, status, sort_order) SELECT 'HP CodeWars', 'One day, dozens of problems, hundreds of students in one room.', '', NULL, '', 'upcoming', 1 WHERE NOT EXISTS (SELECT 1 FROM competitions WHERE name = 'HP CodeWars');
INSERT INTO competitions (name, description, result, event_date, url, status, sort_order) SELECT 'Lockheed Martin AI Quest', 'AI Quest and related challenges, run by Lockheed Martin.', '2nd place, 2025-26 season', NULL, '', 'upcoming', 2 WHERE NOT EXISTS (SELECT 1 FROM competitions WHERE name = 'Lockheed Martin AI Quest');

-- Puzzle Archive
INSERT INTO puzzles (title, prompt, answer, source, posted_at, revealed) SELECT 'The Twelve Coins', 'You have 12 coins. One is lighter. Find it in three weighings.', 'Weighing 1: split the 12 coins into three groups of 4 -- A, B, C. Weigh A against B.
  - If they balance, the light coin is among the 4 in C.
  - If they do not, the light coin is in whichever group of 4 was lighter (the side that went up).

Weighing 2: take those 4 suspect coins and split them into two pairs. Weigh pair 1 against pair 2. The light coin is in whichever pair is lighter.

Weighing 3: weigh the two coins in that pair against each other. The lighter one is the answer.', 'meeting opener', '2026-08-18', 1 WHERE NOT EXISTS (SELECT 1 FROM puzzles WHERE title = 'The Twelve Coins');

-- Editable page text
INSERT OR IGNORE INTO settings (key, value) VALUES ('club_name', 'Plano East CS Club');
INSERT OR IGNORE INTO settings (key, value) VALUES ('school_name', 'Plano East Senior High School');
INSERT OR IGNORE INTO settings (key, value) VALUES ('tagline', 'Build things. Win things. Get better together.');
INSERT OR IGNORE INTO settings (key, value) VALUES ('prize_title', 'Meta Ray-Ban Display Glasses');
INSERT OR IGNORE INTO settings (key, value) VALUES ('prize_blurb', 'First place at the end of the year takes home a pair of Meta Ray-Bans. Points are earned all year — every meeting, every project, every competition counts.');
INSERT OR IGNORE INTO settings (key, value) VALUES ('about_heading', 'About the club');
INSERT OR IGNORE INTO settings (key, value) VALUES ('about_body', 'We are the computer science club at Plano East Senior High School. We meet to build software, break into things we are allowed to break into, enter competitions, and help each other get good.
You do not need experience to join. Half of the people here started by showing up and asking what a terminal was. The other half are happy to tell you.

## How points work
Points are awarded by club officers for anything that moves you or the club forward. Every award is logged with a reason, so you can always see exactly where your points came from on your profile page.

- Showing up to a meeting: 2-5 points
- Finishing a project and demoing it: 15-30 points
- Entering a competition: 20-40 points
- Placing in a competition: 40-60 points
- Teaching a workshop or mentoring someone: 20-25 points
- Helping run a club event: 10-20 points

The member in first place at the end of the year wins a pair of Meta Ray-Bans.

## Meetings
Check the club Discord and the school announcements for the current meeting time and room.');
INSERT OR IGNORE INTO settings (key, value) VALUES ('discord_url', '');
INSERT OR IGNORE INTO settings (key, value) VALUES ('email', '');
INSERT OR IGNORE INTO settings (key, value) VALUES ('join_intro', 'No experience needed. Beginners and returning competitors are both covered -- see the Curriculum page for what that looks like week to week.');
INSERT OR IGNORE INTO settings (key, value) VALUES ('join_consent_url', 'https://myforms.pisd.edu/Forms/ParentClubConsent');
INSERT OR IGNORE INTO settings (key, value) VALUES ('join_classroom_code', '');
INSERT OR IGNORE INTO settings (key, value) VALUES ('join_meeting_info', '');
INSERT OR IGNORE INTO settings (key, value) VALUES ('meetings_calendar_embed_url', '');
INSERT OR IGNORE INTO settings (key, value) VALUES ('meetings_calendar_subscribe_url', '');
